name: news_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#E9EEFA"
  image: "assets/splash/splash_image.png"

  color_dark: "#1A1A1A"
  image_dark: "assets/splash/splash_image_dark.png"

  android_12:
    color: "#E9EEFA"
    image: "assets/splash/splash_image.png"

    color_dark: "#1A1A1A"
    image_dark: "assets/splash/splash_image_dark.png"

flutter:
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
